<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9L9DESM" failures="4" tests="8" name="PetTests" time="10.432" errors="0" timestamp="2025-04-22T21:38:17 CEST">
  <testcase classname="api.tests.StoreTests" name="testCreateOrder" time="3.384"/>
  <testcase classname="api.tests.StoreTests" name="testValidOrder" time="1.556"/>
  <testcase classname="api.tests.StoreTests" name="testGetInventory" time="0.917">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at api.tests.StoreTests.testGetInventory(StoreTests.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetInventory -->
  <testcase classname="api.tests.StoreTests" name="testDeleteValidOrder" time="0.961"/>
  <testcase classname="api.tests.StoreTests" name="testGetOrderWithInvalidId" time="1.115"/>
  <testcase classname="api.tests.StoreTests" name="testDeleteInvalidOrder" time="0.765">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at api.tests.StoreTests.testDeleteInvalidOrder(StoreTests.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteInvalidOrder -->
  <testcase classname="api.tests.StoreTests" name="testCreateOrderWithEmptyPayload" time="0.747">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at api.tests.StoreTests.testCreateOrderWithEmptyPayload(StoreTests.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrderWithEmptyPayload -->
  <testcase classname="api.tests.StoreTests" name="testCreateOrderWithNegativePetId" time="0.619">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at api.tests.StoreTests.testCreateOrderWithNegativePetId(StoreTests.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrderWithNegativePetId -->
</testsuite> <!-- PetTests -->
